# Generated by Django 4.0.3 on 2022-04-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='content',
            new_name='introduction',
        ),
    ]
