# Generated by Django 4.0.3 on 2022-06-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('P', 'Side Project'), ('A', 'Art'), ('N', 'Note'), ('I', 'Idea')], default='P', max_length=1),
        ),
    ]
